"""Drift guard: the committed walk-Skill triple must equal the runtime renderer.

`skills/{walk,walk-observer,walk-inline}/SKILL.md` are derived artifacts of
`guide_cli.resources.render_*` (regenerated by `just render`). If the runtime
renderer changes and the committed files aren't re-rendered, this fails — the
cue to re-run the recipe.

This is the ONLY test that reaches into the runtime: it's marked
`requires_runtime` and skips cleanly when `guide_cli` isn't importable, so the
runtime-source-free core suite (`pytest -m "not requires_runtime"`, or any env
without guide-cli) stays green without it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("agentguides.resources")

from agentguides.resources import render_router_skill, render_walk_skill  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]

# (mode, capability, skill_name) spec — single source of truth, kept in sync
# with scripts/render_plugin_skills.py.
EXPECTED = {
    "walk": render_router_skill(default_mode="observer"),
    "walk-observer": render_walk_skill(
        mode="observer", capability="full", skill_name="walk-observer"
    ),
    "walk-inline": render_walk_skill(
        mode="inline", capability="low", skill_name="walk-inline"
    ),
}


@pytest.mark.requires_runtime
@pytest.mark.parametrize("skill", sorted(EXPECTED))
def test_committed_skill_matches_renderer(skill: str) -> None:
    committed = (REPO_ROOT / "skills" / skill / "SKILL.md").read_text(encoding="utf-8")
    assert committed == EXPECTED[skill], (
        f"skills/{skill}/SKILL.md is stale — run `just render`"
    )
